services:
  rails:
    build: ./rails/backend
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - rails_tmp:/rails/tmp
      - rails_storage:/rails/storage
    ports:
      - "3000:3000"
    tmpfs:
      - /tmp

  node:
    build: ./node
    volumes:
      - node_logs:/app/logs

volumes:
  rails_tmp:
  rails_storage:
  node_logs:

